databases:
  - name: stock-db
    plan: free

services:
  - type: web
    name: stock-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 8000 --ws websockets
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: stock-db
          property: connectionString
